include: package:very_good_analysis/analysis_options.4.0.0.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_required_param: error
    missing_return: error

  exclude:
    - [ lib/gen/** ]
    - /*.g.dart
    - '**/*.g.dart'
    - '**/*.gen.dart'

linter:
  rules:
    public_member_api_docs: false
