name: dota_online
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^6.1.0
  auto_route_generator: ^6.1.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  get_it: ^7.3.0
  google_fonts: ^4.0.3
  intl: ^0.17.0
  json_annotation: ^4.8.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
