// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hero_stats.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_HeroStats _$$_HeroStatsFromJson(Map<String, dynamic> json) => _$_HeroStats(
      id: json['id'] as int?,
      name: json['name'] as String?,
      localizedName: json['localizedName'] as String?,
      primaryAttr: json['primaryAttr'] as String?,
      attackType: json['attackType'] as String?,
      roles:
          (json['roles'] as List<dynamic>?)?.map((e) => e as String).toList(),
      img: json['img'] as String?,
      icon: json['icon'] as String?,
      baseHealth: json['baseHealth'] as int?,
      baseHealthRegen: (json['baseHealthRegen'] as num?)?.toDouble(),
      baseMana: json['baseMana'] as int?,
      baseManaRegen: (json['baseManaRegen'] as num?)?.toDouble(),
      baseArmor: (json['baseArmor'] as num?)?.toDouble(),
      baseMr: json['baseMr'] as int?,
      baseAttackMin: json['baseAttackMin'] as int?,
      baseAttackMax: json['baseAttackMax'] as int?,
      baseStr: json['baseStr'] as int?,
      baseAgi: json['baseAgi'] as int?,
      baseInt: json['baseInt'] as int?,
      strGain: (json['strGain'] as num?)?.toDouble(),
      agiGain: (json['agiGain'] as num?)?.toDouble(),
      intGain: (json['intGain'] as num?)?.toDouble(),
      attackRange: json['attackRange'] as int?,
      projectileSpeed: json['projectileSpeed'] as int?,
      attackRate: (json['attackRate'] as num?)?.toDouble(),
      baseAttackTime: json['baseAttackTime'] as int?,
      attackPoint: (json['attackPoint'] as num?)?.toDouble(),
      moveSpeed: json['moveSpeed'] as int?,
      turnRate: (json['turnRate'] as num?)?.toDouble(),
      cmEnabled: json['cmEnabled'] as bool?,
      legs: json['legs'] as int?,
      dayVision: json['dayVision'] as int?,
      nightVision: json['nightVision'] as int?,
      heroId: json['heroId'] as int?,
      turboPicks: json['turboPicks'] as int?,
      turboWins: json['turboWins'] as int?,
      proBan: json['proBan'] as int?,
      proWin: json['proWin'] as int?,
      proPick: json['proPick'] as int?,
      the1Pick: json['the1Pick'] as int?,
      the1Win: json['the1Win'] as int?,
      the2Pick: json['the2Pick'] as int?,
      the2Win: json['the2Win'] as int?,
      the3Pick: json['the3Pick'] as int?,
      the3Win: json['the3Win'] as int?,
      the4Pick: json['the4Pick'] as int?,
      the4Win: json['the4Win'] as int?,
      the5Pick: json['the5Pick'] as int?,
      the5Win: json['the5Win'] as int?,
      the6Pick: json['the6Pick'] as int?,
      the6Win: json['the6Win'] as int?,
      the7Pick: json['the7Pick'] as int?,
      the7Win: json['the7Win'] as int?,
      the8Pick: json['the8Pick'] as int?,
      the8Win: json['the8Win'] as int?,
      nullPick: json['nullPick'] as int?,
      nullWin: json['nullWin'] as int?,
    );

Map<String, dynamic> _$$_HeroStatsToJson(_$_HeroStats instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'localizedName': instance.localizedName,
      'primaryAttr': instance.primaryAttr,
      'attackType': instance.attackType,
      'roles': instance.roles,
      'img': instance.img,
      'icon': instance.icon,
      'baseHealth': instance.baseHealth,
      'baseHealthRegen': instance.baseHealthRegen,
      'baseMana': instance.baseMana,
      'baseManaRegen': instance.baseManaRegen,
      'baseArmor': instance.baseArmor,
      'baseMr': instance.baseMr,
      'baseAttackMin': instance.baseAttackMin,
      'baseAttackMax': instance.baseAttackMax,
      'baseStr': instance.baseStr,
      'baseAgi': instance.baseAgi,
      'baseInt': instance.baseInt,
      'strGain': instance.strGain,
      'agiGain': instance.agiGain,
      'intGain': instance.intGain,
      'attackRange': instance.attackRange,
      'projectileSpeed': instance.projectileSpeed,
      'attackRate': instance.attackRate,
      'baseAttackTime': instance.baseAttackTime,
      'attackPoint': instance.attackPoint,
      'moveSpeed': instance.moveSpeed,
      'turnRate': instance.turnRate,
      'cmEnabled': instance.cmEnabled,
      'legs': instance.legs,
      'dayVision': instance.dayVision,
      'nightVision': instance.nightVision,
      'heroId': instance.heroId,
      'turboPicks': instance.turboPicks,
      'turboWins': instance.turboWins,
      'proBan': instance.proBan,
      'proWin': instance.proWin,
      'proPick': instance.proPick,
      'the1Pick': instance.the1Pick,
      'the1Win': instance.the1Win,
      'the2Pick': instance.the2Pick,
      'the2Win': instance.the2Win,
      'the3Pick': instance.the3Pick,
      'the3Win': instance.the3Win,
      'the4Pick': instance.the4Pick,
      'the4Win': instance.the4Win,
      'the5Pick': instance.the5Pick,
      'the5Win': instance.the5Win,
      'the6Pick': instance.the6Pick,
      'the6Win': instance.the6Win,
      'the7Pick': instance.the7Pick,
      'the7Win': instance.the7Win,
      'the8Pick': instance.the8Pick,
      'the8Win': instance.the8Win,
      'nullPick': instance.nullPick,
      'nullWin': instance.nullWin,
    };
