// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hero_stats.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_HeroStats _$$_HeroStatsFromJson(Map<String, dynamic> json) => _$_HeroStats(
      id: json['id'] as int?,
      name: json['name'] as String?,
      localizedName: json['localized_name'] as String?,
      primaryAttr: json['primary_attr'] as String?,
      attackType: json['attack_type'] as String?,
      roles:
          (json['roles'] as List<dynamic>?)?.map((e) => e as String).toList(),
      img: json['img'] as String?,
      icon: json['icon'] as String?,
      baseHealth: json['base_health'] as int?,
      baseHealthRegen: (json['base_health_regen'] as num?)?.toDouble(),
      baseMana: json['base_mana'] as int?,
      baseManaRegen: (json['base_mana_regen'] as num?)?.toDouble(),
      baseArmor: (json['base_armor'] as num?)?.toDouble(),
      baseMr: json['base_mr'] as int?,
      baseAttackMin: json['base_attack_min'] as int?,
      baseAttackMax: json['base_attack_max'] as int?,
      baseStr: json['base_str'] as int?,
      baseAgi: json['base_agi'] as int?,
      baseInt: json['base_int'] as int?,
      strGain: (json['str_gain'] as num?)?.toDouble(),
      agiGain: (json['agi_gain'] as num?)?.toDouble(),
      intGain: (json['int_gain'] as num?)?.toDouble(),
      attackRange: json['attack_range'] as int?,
      projectileSpeed: json['projectile_speed'] as int?,
      attackRate: (json['attack_rate'] as num?)?.toDouble(),
      baseAttackTime: json['base_attack_time'] as int?,
      attackPoint: (json['attack_point'] as num?)?.toDouble(),
      moveSpeed: json['move_speed'] as int?,
      turnRate: (json['turn_rate'] as num?)?.toDouble(),
      cmEnabled: json['cm_enabled'] as bool?,
      legs: json['legs'] as int?,
      dayVision: json['day_vision'] as int?,
      nightVision: json['night_vision'] as int?,
      heroId: json['hero_id'] as int?,
      turboPicks: json['turbo_picks'] as int?,
      turboWins: json['turbo_wins'] as int?,
      proBan: json['pro_ban'] as int?,
      proWin: json['pro_win'] as int?,
      proPick: json['pro_pick'] as int?,
      the1Pick: json['the1_pick'] as int?,
      the1Win: json['the1_win'] as int?,
      the2Pick: json['the2_pick'] as int?,
      the2Win: json['the2_win'] as int?,
      the3Pick: json['the3_pick'] as int?,
      the3Win: json['the3_win'] as int?,
      the4Pick: json['the4_pick'] as int?,
      the4Win: json['the4_win'] as int?,
      the5Pick: json['the5_pick'] as int?,
      the5Win: json['the5_win'] as int?,
      the6Pick: json['the6_pick'] as int?,
      the6Win: json['the6_win'] as int?,
      the7Pick: json['the7_pick'] as int?,
      the7Win: json['the7_win'] as int?,
      the8Pick: json['the8_pick'] as int?,
      the8Win: json['the8_win'] as int?,
      nullPick: json['null_pick'] as int?,
      nullWin: json['null_win'] as int?,
    );

Map<String, dynamic> _$$_HeroStatsToJson(_$_HeroStats instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'localized_name': instance.localizedName,
      'primary_attr': instance.primaryAttr,
      'attack_type': instance.attackType,
      'roles': instance.roles,
      'img': instance.img,
      'icon': instance.icon,
      'base_health': instance.baseHealth,
      'base_health_regen': instance.baseHealthRegen,
      'base_mana': instance.baseMana,
      'base_mana_regen': instance.baseManaRegen,
      'base_armor': instance.baseArmor,
      'base_mr': instance.baseMr,
      'base_attack_min': instance.baseAttackMin,
      'base_attack_max': instance.baseAttackMax,
      'base_str': instance.baseStr,
      'base_agi': instance.baseAgi,
      'base_int': instance.baseInt,
      'str_gain': instance.strGain,
      'agi_gain': instance.agiGain,
      'int_gain': instance.intGain,
      'attack_range': instance.attackRange,
      'projectile_speed': instance.projectileSpeed,
      'attack_rate': instance.attackRate,
      'base_attack_time': instance.baseAttackTime,
      'attack_point': instance.attackPoint,
      'move_speed': instance.moveSpeed,
      'turn_rate': instance.turnRate,
      'cm_enabled': instance.cmEnabled,
      'legs': instance.legs,
      'day_vision': instance.dayVision,
      'night_vision': instance.nightVision,
      'hero_id': instance.heroId,
      'turbo_picks': instance.turboPicks,
      'turbo_wins': instance.turboWins,
      'pro_ban': instance.proBan,
      'pro_win': instance.proWin,
      'pro_pick': instance.proPick,
      'the1_pick': instance.the1Pick,
      'the1_win': instance.the1Win,
      'the2_pick': instance.the2Pick,
      'the2_win': instance.the2Win,
      'the3_pick': instance.the3Pick,
      'the3_win': instance.the3Win,
      'the4_pick': instance.the4Pick,
      'the4_win': instance.the4Win,
      'the5_pick': instance.the5Pick,
      'the5_win': instance.the5Win,
      'the6_pick': instance.the6Pick,
      'the6_win': instance.the6Win,
      'the7_pick': instance.the7Pick,
      'the7_win': instance.the7Win,
      'the8_pick': instance.the8Pick,
      'the8_win': instance.the8Win,
      'null_pick': instance.nullPick,
      'null_win': instance.nullWin,
    };
